#!/bin/bash
# Chord Manual Rollback Script
# Switches traffic back to the previous stack
#
# Usage:
#   ./rollback.sh           # Switch to inactive stack
#   ./rollback.sh --to blue # Switch to specific stack

set -e

# ===========================================
# Configuration
# ===========================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.deploy.yml"
STATE_FILE="$PROJECT_DIR/.deploy-state"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ===========================================
# Functions
# ===========================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

get_active_stack() {
    if [ -f "$STATE_FILE" ]; then
        cat "$STATE_FILE"
    else
        echo "none"
    fi
}

set_active_stack() {
    echo "$1" > "$STATE_FILE"
}

get_api_port() {
    local stack=$1
    if [ "$stack" == "blue" ]; then
        echo "5000"
    else
        echo "5002"
    fi
}

get_frontend_port() {
    local stack=$1
    if [ "$stack" == "blue" ]; then
        echo "3000"
    else
        echo "3002"
    fi
}

check_stack_running() {
    local stack=$1
    local api_container="chord-api-$stack"
    local frontend_container="chord-frontend-$stack"
    
    if docker ps --format '{{.Names}}' | grep -q "^${api_container}$"; then
        if docker ps --format '{{.Names}}' | grep -q "^${frontend_container}$"; then
            return 0
        fi
    fi
    
    return 1
}

update_caddy() {
    local stack=$1
    local api_port=$(get_api_port "$stack")
    local frontend_port=$(get_frontend_port "$stack")
    
    log_info "Updating Caddy to route to $stack stack..."
    
    # Generate Caddyfile with correct upstream
    cat > "$PROJECT_DIR/backend/Caddyfile" << EOF
# Chord Caddy Configuration
# Auto-generated by rollback.sh - Active stack: $stack

{
    admin off
}

\${DOMAIN:localhost} {
    # API endpoints
    handle /api/* {
        reverse_proxy localhost:$api_port
    }

    # SignalR WebSocket hubs
    handle /hubs/* {
        reverse_proxy localhost:$api_port
    }

    # Health check
    handle /health {
        reverse_proxy localhost:$api_port
    }

    # LiveKit WebSocket
    handle /livekit/* {
        reverse_proxy livekit:7880
    }

    # MinIO file uploads
    handle /uploads/* {
        uri strip_prefix /uploads
        reverse_proxy minio:9000
    }

    # Frontend (catch-all)
    handle /* {
        reverse_proxy localhost:$frontend_port
    }
}
EOF
    
    # Reload Caddy
    if docker ps --format '{{.Names}}' | grep -q "chord-caddy"; then
        docker exec chord-caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || \
        docker restart chord-caddy
    fi
    
    log_success "Caddy updated"
}

show_status() {
    echo ""
    echo "Current Status:"
    echo "==============="
    
    local active=$(get_active_stack)
    echo "Active stack: $active"
    echo ""
    
    echo "Blue stack:"
    if check_stack_running "blue"; then
        echo "  ✓ Running"
        echo "    API: http://localhost:5000"
        echo "    Frontend: http://localhost:3000"
    else
        echo "  ✗ Not running"
    fi
    
    echo ""
    echo "Green stack:"
    if check_stack_running "green"; then
        echo "  ✓ Running"
        echo "    API: http://localhost:5001"
        echo "    Frontend: http://localhost:3001"
    else
        echo "  ✗ Not running"
    fi
    
    echo ""
}

# ===========================================
# Main
# ===========================================

TARGET_STACK=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --to)
            TARGET_STACK="$2"
            if [[ "$TARGET_STACK" != "blue" && "$TARGET_STACK" != "green" ]]; then
                log_error "Invalid stack: $TARGET_STACK (must be 'blue' or 'green')"
                exit 1
            fi
            shift 2
            ;;
        --status)
            show_status
            exit 0
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --to STACK    Switch to specific stack (blue or green)"
            echo "  --status      Show current deployment status"
            echo "  -h, --help    Show this help message"
            echo ""
            echo "Without options, switches to the inactive stack."
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo ""
echo "╔═══════════════════════════════════════╗"
echo "║        Chord Manual Rollback          ║"
echo "╚═══════════════════════════════════════╝"
echo ""

# Get current state
ACTIVE_STACK=$(get_active_stack)

# Determine target stack
if [ -z "$TARGET_STACK" ]; then
    if [ "$ACTIVE_STACK" == "blue" ]; then
        TARGET_STACK="green"
    elif [ "$ACTIVE_STACK" == "green" ]; then
        TARGET_STACK="blue"
    else
        log_error "No active stack found. Cannot determine rollback target."
        log_info "Use --to <stack> to specify target stack."
        exit 1
    fi
fi

log_info "Current active stack: $ACTIVE_STACK"
log_info "Rolling back to: $TARGET_STACK"

# Check if target stack is running
if ! check_stack_running "$TARGET_STACK"; then
    log_error "$TARGET_STACK stack is not running!"
    log_info "Starting $TARGET_STACK stack..."
    
    docker compose -f "$COMPOSE_FILE" --profile "$TARGET_STACK" up -d
    
    # Wait for startup
    log_info "Waiting for $TARGET_STACK stack to start..."
    sleep 15
    
    if ! check_stack_running "$TARGET_STACK"; then
        log_error "Failed to start $TARGET_STACK stack"
        exit 1
    fi
fi

# Switch traffic
update_caddy "$TARGET_STACK"

# Update state
set_active_stack "$TARGET_STACK"

echo ""
log_success "Rollback complete!"
log_success "Active stack: $TARGET_STACK"
echo ""

# Show status
show_status


